# Credits

This is heavily based on https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used.


PyTorch a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a $5\times 3$ matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[1.5044e+02, 8.4078e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2260, 0.5227, 0.5121],
        [0.2772, 0.7341, 0.7974],
        [0.4987, 0.7110, 0.8417],
        [0.9425, 0.5001, 0.8831],
        [0.6930, 0.9265, 0.6483]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE**: `torch.Size` is in fact a tuple, so it supports the same operations that a tuple supports.

In [5]:
x[1:3] = 2
print(x)

tensor([[0.2260, 0.5227, 0.5121],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.9425, 0.5001, 0.8831],
        [0.6930, 0.9265, 0.6483]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [10]:
a = torch.Tensor(2, 17)
b = torch.FloatTensor(3, 1)
c = torch.LongTensor(5, 2, 1)
print(a)
print(b)
print(c)

c[:, :, :] = 7
print(c)

d = torch.ByteTensor(5, )
d[1:4] = 1
print(d)

tensor([[8.4642e-11, 3.5950e-41, 0.0000e+00, 0.0000e+00, 6.6918e+27, 3.5942e-41,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         7.5381e+27, 4.1861e-41, 6.6913e+27, 3.5942e-41, 6.6913e+27],
        [3.5942e-41, 4.5850e-42, 0.0000e+00, 7.5127e+27, 4.1861e-41, 2.0223e-19,
         9.1840e-41, 6.8179e+22, 2.7523e+23, 6.6925e+27, 3.5942e-41, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[1.0139e-10],
        [3.5950e-41],
        [0.0000e+00]])
tensor([[[    110188171442754],
         [                  0]],

        [[                  0],
         [                  0]],

        [[    110161616175104],
         [7363726485869454435]],

        [[7148388425482187565],
         [3256159938081011558]],

        [[3545567882495944244],
         [    110163280486712]]])
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
    

## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.2847, 1.1975, 1.0273],
        [2.1843, 2.4308, 2.8723],
        [2.4924, 2.6637, 2.8269],
        [1.6467, 0.5747, 1.8213],
        [1.4355, 1.0532, 1.2421]])


### 2.2 Addition: syntax 2

In [12]:
print(torch.add(x, y))

tensor([[0.2847, 1.1975, 1.0273],
        [2.1843, 2.4308, 2.8723],
        [2.4924, 2.6637, 2.8269],
        [1.6467, 0.5747, 1.8213],
        [1.4355, 1.0532, 1.2421]])


### 2.3 Addition: giving an output tensor

In [13]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.2847, 1.1975, 1.0273],
        [2.1843, 2.4308, 2.8723],
        [2.4924, 2.6637, 2.8269],
        [1.6467, 0.5747, 1.8213],
        [1.4355, 1.0532, 1.2421]])


### 2.4 Addition: in-place

adds `x` to `y`

In [14]:
y.add_(x)
print(y)

tensor([[0.2847, 1.1975, 1.0273],
        [2.1843, 2.4308, 2.8723],
        [2.4924, 2.6637, 2.8269],
        [1.6467, 0.5747, 1.8213],
        [1.4355, 1.0532, 1.2421]])


**NOTE**: Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [15]:
print(x[:, 1])

tensor([0.5227, 2.0000, 2.0000, 0.5001, 0.9265])


**Read later**: 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiplication of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [22]:
x = torch.ones(2, 3)
y = torch.zeros(2, 3)
z = torch.mul(x, 2)
print(z)
z = torch.mul(x, y)
print(z)

y.mul_(x)
print(y)

z = torch.div(x, 2)
print(z)

x = torch.randn(2, 4)
y = torch.randn(4, 2)
z = torch.mm(x, y)
print(z)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])
tensor([[ 0.4581, -1.0209],
        [-1.1763,  0.3705]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [23]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.])


See how the numpy array changed in value: the `numpy()` method provides a *view* of the original tensor, not a copy.

In [26]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [27]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a NumPy array
3. now convert it back to a torch tensor

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [28]:
x = torch.ones(5, 2)
x_np = x.numpy()
x_tensor = torch.from_numpy(x_np)
print(x)
print(x_np)
print(x_tensor)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [30]:
x = torch.ones(5, 2)
y = torch.ones(5, 2)
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # Notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # This is meant as a tensor to be run on the GPU.
    # The .cuda() does this to any parameter it is applied to.
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]], device='cuda:0')
